---
title: "Class12"
author: "Baiden Gallo"
date: "2026-10-05"
output: 
html_document:
  toc: TRUE
    toc_float: true
    number_sections: true
    code_download: true
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
year = 2025

crash_url = paste0('https://www.planecrashinfo.com/', year, '/', year, '.htm')

crash_page <- rvest::read_html(crash_url, encoding = "ISO-8859-1")

# This should now print without the error
crash_page

# How many <table> elements are on the page?
crash_tables <- crash_page |>
  rvest::html_elements("table") |>
  rvest::html_table()

#From a cleaning perspective
#[1] translate into DF instead of list
#[2] replace headers with row 1, then delete row 1
#[3] change date from chr to date
#[4] complex cleaning to split info within cell into separate columns

crash_df = crash_tables[[1]] #subset a list

colnames(crash_df) = crash_df[1, ]
crash_df = crash_df[-1, ]

#convert date column into date type
crash_df= crash_df |>
  dplyr::mutate(Date= lubridate::dmy(Date))

dplyr::glimpse(crash_df)
```

#in class practice game
```{r}
#Q1
page = rvest::read_html("https://isa401-salvage.vercel.app/registry?start=1")
classes = page |>
  rvest::html_elements("Dreadnoughts") |>
  rvest::html_text2()
length(classes)   # check this first: one per card

#Q3
base = "https://isa401-salvage.vercel.app"
starts = seq(from = 1, to = 351, by = 50)
pages = vector("list", length(starts)) #initialize list, similar for df
for (i in seq_along(starts)) {
  pg = rvest::read_html(paste0(base, "/registry?start=", starts[i]))
  pages[[i]] = data.frame(
    class = pg |> rvest::html_elements("div > ul > li:nth-child(1) > span") |> 
      rvest::html_text2(),
    value = pg |> rvest::html_elements("div > ul > li:nth-child(3) > span") |> 
      rvest::html_text2() |> readr::parse_number()
  )
  Sys.sleep(1)   # robots.txt asks for it
}
registry = dplyr::bind_rows(pages)   # 400 rows?

dreadnought_df = registry |>
dplyr::filter(class== "Dreadnought")

sum(dreadnought_df$value)
```



```{r}
type_course = ellmer::type_object(
  code = ellmer::type_string(
    "Subject and number. For example, ISA 401"
  ),
  name = ellmer::type_string(
    "Name of the course, without the code"
  ),
  credit_hours = ellmer::type_integer(
    "The number in parentheses after the name",
    required = FALSE
  ),
  prereqs = ellmer::type_string(
    "The prerequisite[s] for this course",
    required = FALSE
  )
)
```

#ISA 125 extraction
```{r isa125}
chat= ellmer::chat_openai(
  model= "gpt-5.6-luna"
)
isa125_courseblock= rvest::read_html("https://bulletin.miamioh.edu/courses-instruction/isa/") |>
  rvest::html_elements("#sc_sccoursedescs > div:nth-child(1)")|>
  rvest::html_text2()
  
chat$chat_structured(
  isa125_courseblock,
  type= ellmer::type_object(
    #code is name of first element returned in sublist
    code= ellmer::type_string(
    #type string forces that element to be of type chr
    description= "3 letter abbreviation for course and its number, ex. ISA 999"
    ),
    name= ellmer::type_string(
      description= "title of the course without 3 letter abbreviation and number, ex. Intro to macroeconomics. Do not return a period after the name"
    ),
    cr_hr= ellmer::type_integer(description= "number of credits show in parentheses after course code and title")
  )
)
```


#All 50 ISA courses
```{r}
chat= ellmer::chat_openai(
  model= "gpt-5.6-luna"
)

course_vec= rvest::read_html("https://bulletin.miamioh.edu/courses-instruction/isa/")|>
  rvest::html_elements("div.courseblock") |> rvest::html_text2()

course_list= as.list(course_vec) #makes it a list

type_course= ellmer::type_object(
    #code is name of first element returned in sublist
    code= ellmer::type_string(
    #type string forces that element to be of type chr
    description= "3 letter abbreviation for course and its number, ex. ISA 999"
    ),
    name= ellmer::type_string(
      description= "title of the course without 3 letter abbreviation and number, ex. Intro to macroeconomics. Do not return a period after the name"
    ),
    cr_hr= ellmer::type_integer(description= "number of credits show in parentheses after course code and title")
  )

isa_df= ellmer::parallel_chat_structured(
  chat,
  prompts= course_list,
  type= type_course,
  include_tokens= T, include_cost= T
)

sum(isa_df$cost)
```



