---
title: "Class13"
author: "Baiden Gallo"
date: "2026-10-07"
output: 
html_document:
  toc: TRUE
    toc_float: true
    number_sections: true
    code_download: true
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#table
```{r}
skills_long = skills_wide |>
  tidyr::pivot_longer(cols = c("2024", "2025", "2026"),
                      names_to = "year", values_to = "share")
```

#rows become columns
```{r}
skills_wide = skills_long |>
  tidyr::pivot_wider(names_from = year, values_from = share)
```

#separate columns
```{r}
crash_three = crash_two |>
  tidyr::separate(fatalities,
                  into = c("air_fatalities", "passengers", "ground"))
```

#unite columns
```{r}
crash_two = crash_three |>
  tidyr::unite(col = "fatalities", air_fatalities, passengers, ground,
               sep = "/")
```


#plane crash example

```{r}
crash_url = paste0("https://www.planecrashinfo.com/", year, "/", year, ".htm")

crash_page <- rvest::read_html(crash_url, encoding = "ISO-8859-1")

crash_page |>
  rvest::html_elements("td:nth-child(1) > font > a")|>
  rvest::html_text2() <- dates
  
crash_page |>
  rvest::html_elements("td:nth-child(2) > font")|>
  rvest::html_text2() <- loc_op

crash_page |>
  rvest::html_elements("td:nth-child(4) > font")|>
  rvest::html_text2() <- fatalities

df= data.frame(dates= dates, loc= loc_op[-1], fatalities= fatalities[-1])|>
  tidyr::separate(loc, into= c("location", "operator",), sep= "\n")|>
  tidyr::separate(fatalities, into= c("plane_fatalities", "pass", "ground_fatalities"))

#this is tidy but not technically clean

dplyr::glimpse(df)
  
```


